JuliaML/TableTransforms.jl

- src/transforms/eigenanalysis.jl
Try to fix #10.
All tests passing locally (not considering that image test that passes/don't aleatory)
> solve unecessary use of inv function

- src/TableTransforms.jl
- src/transforms.jl
- src/transforms/rename.jl
- test/transforms.jl
This should be fully functional, but I think the usage of `push!!` will need to be redesigned to be more functional and efficient like other transforms. That is the place where I think I need a little help: I am not sure how to make it so that I don't need `push!!` and use `𝒯 = (; zip(anames, acols)...)` instead like the rest of the of the transforms.
> wip: implement Rename transform

- README.md
MLJ 0.17 now provides a facility to build pipelines which does not require macros.
> Update README description of MLJ to reflect non-macro pipelines

- src/transforms/functional.jl
- test/runtests.jl
- test/transforms.jl
A small change to make the Functional type stable
> Type Stable Functional

- src/transforms/select.jl
- test/transforms.jl
Update Select and Reject to add Regex support.
Fix #14
> New Select and Reject

- Project.toml
- src/TableTransforms.jl
- src/transforms/select.jl
- test/transforms.jl
This PR implements a lazy type for selections/rejections.
Fix #16
> TableSelection

- src/transforms/colspec.jl
- src/transforms/filter.jl
- src/transforms/select.jl
- test/transforms.jl
To implement the ColSpec interface, the following steps must be performed:
1 - add colspec fied:
```julia
struct MyTransform{S<:ColSpec,#= other type params =#}
colspec::S
end
```
2 - using `_filter(colspec, cols)` internal function:
```julia
function apply(transform::MyTransform, table)
allcols = Tables.columnnames(table)
cols = _filter(transform.colspec, allcols)
end
```
> Implementing ColSpec interface in Select and Reject

- src/transforms/filter.jl
- test/transforms.jl
This PR implements the ColSpec interface in DropMissing. This is the last part of the ColSpec interface implementation in the current code.
> Implementing ColSpec interface in DropMissing

- src/transforms/filter.jl
- test/transforms.jl
This PR adds a post-processing in the apply function of the DropMissing transformation and a pre-processing in the revert function.
This is necessary so that the type of columns where the DropMissing transformation will be applied is `T` instead of `Union{Missing,T}` .
> Avoid `Union{Missing,T}` in columns after DropMissing

- src/transforms/coalesce.jl
Update code style of Coalesce to match with code style of Replace.
> Update code style of Coalesce transform

- src/transforms/coalesce.jl
- src/transforms/coerce.jl
- src/transforms/identity.jl
- src/transforms/rename.jl
- src/transforms/replace.jl
Updated docstrings for:
- Rename
- Replace
- Coalesce
- Coerce
- Identity
> Updated docstrings

- src/TableTransforms.jl
- src/transforms/identity.jl
> Unexport internal types and functions; Remove unnecessary example

- src/transforms/functional.jl
- test/transforms.jl
This PR redesigns `Functional` implementation to add support for applying functions to specific columns.
The following constructor has been added:
```julia
Functional(col₁ => func₁, col₂ => func₂, ..., colₙ => funcₙ)
```
closes #59
> New Functional

- src/transforms/select.jl
This PR redesigns TableSelection implementation to accept RowTable.
> Redesign TableSelection implementation

- src/colspec.jl
- src/transforms.jl
- src/transforms/coerce.jl
- src/transforms/eigenanalysis.jl
- src/transforms/filter.jl
- src/transforms/functional.jl
- src/transforms/parallel.jl
- src/transforms/rename.jl
- src/transforms/select.jl
- test/transforms.jl
> `Tables.columnnames(table)` => `Tables.columnnames(cols)`

- src/transforms/select.jl
- test/transforms.jl
Should fix the issue #76. I just used `Any` since it does not seem to make a performance difference.
Also the [manual](https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-elaborate-container-types) notes that elaborated container types should be avoided.
For performance I used the following test functions:
```julia
function bench(inputs)
p, table = inputs
newtable, cache = apply(p, table)
return revert(p, newtable, cache)
end
function setup(n, T)
table = (; zip([Symbol(:x, k) for k=1:length(T)], [rand(t, n) for t in T])...)
p = Select([rand(findall(x -> x == t, T)) for t in unique(T)]) → Functional(identity)
return p, table
end
```
On 988265e6c7460e1d08c8f79fccd8301a840ba5c7
```julia
julia> @benchmark bench(inputs) setup=(inputs=setup(50000, (Float64, Float64))) …
```
> Fix Select inversion #76

- src/transforms/scale.jl
- test/transforms.jl
As noted by @eliascarv in https://github.com/JuliaML/TableTransforms.jl/issues/76#issuecomment-1128835713 `Scale` always promotes column types to `Float64`. This should fix this issue and make it work with different float types.
> fix: scale no longer converts all floats to Float64

- src/transforms.jl
- test/shows.jl
Examples:
```julia
julia> EigenAnalysis(:VDV)
EigenAnalysis transform
├─ proj = :VDV
├─ maxdim = nothing
└─ pratio = 1.0
julia> EigenAnalysis(:VDV) |> println
EigenAnalysis(:VDV, nothing, 1.0)
julia> Scale(low=0, high=1)
Scale transform
├─ low = 0
└─ high = 1
julia> Scale(low=0, high=1) |> println
Scale(0, 1)
julia> begin
f1 = ZScore()
f2 = Scale()
f3 = Functional(cos)
f4 = MinMax()
pipeline = (f1 → f2) ⊔ (f3 → f4)
end
Parallel
├─ Sequential
│  ├─ ZScore()
│  └─ Scale(0.25, 0.75)
└─ Sequential
├─ Functional(cos)
└─ Scale(0, 1)
julia> pipeline |> println
ZScore() → Scale(0.25, 0.75) ⊔ Functional(cos) → Scale(0, 1)
```
> Add Generic Shows

- src/transforms/select.jl
- test/colspec.jl
- test/shows.jl
- test/transforms.jl
This PR is a major refactoring of the `Select` implementation to add support for selection with renaming.
I also took the liberty of renaming the variables to code style the rest of the TableTransforms.jl code.
I also made small optimizations in the apply function.
closes #106
> New Select implementation

- src/TableTransforms.jl
- src/transforms/sample.jl
- test/shows.jl
- test/transforms.jl
This is a necessary breaking change to avoid the external dependence on StatsBase.jl weights and to make the end-user experience more smooth.
> Refactor Sample

- src/TableTransforms.jl
- src/tabletraits.jl
- src/transforms.jl
- src/transforms/coerce.jl
- src/transforms/coltable.jl
- src/transforms/eigenanalysis.jl
- src/transforms/filter.jl
- src/transforms/functional.jl
- src/transforms/identity.jl
- src/transforms/levels.jl
- src/transforms/onehot.jl
- src/transforms/rename.jl
- src/transforms/rowtable.jl
- src/transforms/sample.jl
- src/transforms/select.jl
- src/transforms/sort.jl
- src/transforms/stdnames.jl
Fixes #114 
This PR generalizes our API to handle metadata. I needed to introduce two new trait functions `divide` and `attach` to be implemented by table types in order to seamlessly integrate with all our transforms.
> Add support for metadata

- src/transforms.jl
- src/transforms/coerce.jl
- src/transforms/coltable.jl
- src/transforms/eigenanalysis.jl
- src/transforms/filter.jl
- src/transforms/functional.jl
- src/transforms/identity.jl
- src/transforms/levels.jl
- src/transforms/onehot.jl
- src/transforms/rename.jl
- src/transforms/rowtable.jl
- src/transforms/sample.jl
- src/transforms/select.jl
- src/transforms/sort.jl
- src/transforms/stdnames.jl
This PR introduces a new preprocess function to be used by transforms such as Filter, Sort, etc. which can be expressed in terms of an intermediate representation (e.g. indices).
> Add preprocess

- src/transforms/parallel.jl
This is a hotfix for the Parallel transform. I started playing with more complex pipelines and realized that we didn't have this case covered in our tests. In a future PR we should consider introducing a dummy table type with metadata in our test suite.
> Fix Parallel transform in the presence of metadata

- src/TableTransforms.jl
- src/transforms.jl
- src/transforms/center.jl
- src/transforms/coalesce.jl
- src/transforms/coerce.jl
- src/transforms/coltable.jl
- src/transforms/eigenanalysis.jl
- src/transforms/filter.jl
- src/transforms/functional.jl
- src/transforms/identity.jl
- src/transforms/levels.jl
- src/transforms/onehot.jl
- src/transforms/quantile.jl
- src/transforms/rename.jl
- src/transforms/replace.jl
- src/transforms/rowtable.jl
- src/transforms/sample.jl
- src/transforms/scale.jl
- src/transforms/select.jl
- src/transforms/sort.jl
- src/transforms/stdnames.jl
- src/transforms/zscore.jl
- test/metatable.jl
Introduces a new abstract `FeatureTransform` type to help in future dispatch rules with other types of `TableTransform`.
> Add FeatureTransform

- src/transforms/scale.jl
- test/shows.jl
- test/transforms/scale.jl
This PR makes Scale constructor simpler and avoids type conversion in `apply(transform, table)`.
> Refactor Scale

- src/tableselection.jl
- test/tableselection.jl
Code:
```julia
julia> using TableTransforms
julia> using Tables
julia> using TypedTables
julia> table = Table(
a = 1:5,
b = 6:10,
c = 11:15,
d = 16:20
);
julia> transf = Select(:a => :x, :d => :y)
Select transform
├─ colspec = [:a, :d]
└─ newnames = [:x, :y]
julia> newtable, cache = apply(transf, table);
julia> newtable
TableSelection
┌───────┬───────┐
│     x │     y │
│ Int64 │ Int64 │
├───────┼───────┤
│     1 │    16 │
│     2 │    17 │
│     3 │    18 │
│     4 │    19 │
│     5 │    20 │
└───────┴───────┘
```
master:
```julia
julia> Tables.getcolumn(newtable, 1)
ERROR: type NamedTuple has no field x
Stacktrace:
[1] getproperty
@ .\Base.jl:38 [inlined]
[2] getcolumn
@ C:\Users\Dev01\.julia\packages\Tables\T7rHm\src\Tables.jl:102 [inlined]
[3] …
```
> Fix bug in `Tables.getcolumn(t::TableSelection, i::Int)`

- src/transforms.jl
- test/transforms/zscore.jl
@juliohm  I fixed the Assertion Error and it is working fine now, then again was getting ```ERROR: MethodError: no method matching getindex(::NamedTuple{(:a, :b), Tuple{Vector{Int64}, Vector{Float64}}}, ::Colon, ::Vector{Symbol})``` for 
```jl
(a=rand(Int,3), b=rand(3)) |> ZScore(:b)
```
I guess the ZScore function expects the input data to be a tabular data structure, like DataFrame or a Table, but the input data in this case is a NamedTuple. Converting into dataframe, I am getting correct output:
```jl
julia> DataFrame((a=rand(Int,3), b=rand(3))) |> ZScore(:b)
3×2 DataFrame
Row │ a                    b
│ Int64                Float64
─────┼────────────────────────────────
1 │ 4442619791281385888  -1.12529
2 │ 7630774422502565167   0.786904
3 │ 1978852580104395244   0.338386
```
> fixed AssertionError

- src/TableTransforms.jl
- src/tablerows.jl
- src/transforms/filter.jl
- test/colspec.jl
- test/distributions.jl
- test/runtests.jl
- test/tablerows.jl
- test/tableselection.jl
- test/transforms/filter.jl
- test/transforms/stdnames.jl
> Implement a generic row iterator

- src/transforms/stdnames.jl
- test/transforms/stdnames.jl
Bug description:
The `uppercasefirst` function is not the corect function for Camel Case, the corect is the `titlecase` function:
```
julia> uppercasefirst("aBc")
"ABc"
julia> titlecase("aBc")
"Abc"
```
> FIX: Use the `titlecase` function in (Upper) Camel Case

- src/transforms/coerce.jl
- test/transforms/coerce.jl
Coerce fails with string colspec   issue #194  fixing
-->  Added extra line in coerce.jl for string implementation
>  Coerce fails with string colspec

- src/assertions.jl
- src/distributions.jl
- src/tableselection.jl
- src/transforms.jl
- src/transforms/dropextrema.jl
- src/transforms/eigenanalysis.jl
- src/transforms/functional.jl
- src/transforms/logratio.jl
- src/transforms/parallel.jl
- src/transforms/remainder.jl
- src/transforms/rename.jl
- src/transforms/scale.jl
Motivation: `@assert` docstring:
```
help?> @assert
@assert cond [text]
Throw an AssertionError if cond is false. Preferred syntax for writing
assertions. Message text is optionally displayed upon assertion failure.
│ Warning
│
│  An assert might be disabled at various optimization levels. Assert
│  should therefore only be used as a debugging tool and not used for
│  authentication verification (e.g., verifying passwords), nor should
│  side effects needed for the function to work correctly be used
│  inside of asserts.
```
> Replace the `assert` macro with the new `_assert` utility function

- src/transforms/rename.jl
- test/Project.toml
- test/transforms/rename.jl
> Rename: Add support for modification function

- src/transforms/coerce.jl
- src/transforms/rename.jl
- test/transforms/coerce.jl
- test/transforms/rename.jl
> Add support for `Coerce(SciType)`

- src/transforms/logratio.jl
- test/transforms/logratio.jl
Fix https://github.com/JuliaEarth/GeoStats.jl/issues/503
> Fix revert of logratio transforms

- src/tableselection.jl
- src/transforms/select.jl
- test/tableselection.jl
- test/transforms/sample.jl
- test/transforms/select.jl
This PR refactors the internal `TableSelection` type to avoid runtime checks in the wrong places. This type is intended for developers of TableTransforms.jl so the only check that should occur about the columns names is in the constructor. All further calls to Tables.getcolumn should assume the existence of columns for performance.
I also refactored the field type to a static tuple to improve the performance in downstream algorithm given the number of columns at compile time. It is also more consistent with other table types that return tuples in Tables.columnnames.
@eliascarv is there any particular reason we used Vector{Symbol} for the names or are we ok replacing it with tuple?
> Refactor TableSelection
